import { RoleBasedAccessControl } from '@/types/types';

export const ROLE_BASED_ACCESS_CONTROL: RoleBasedAccessControl = {
  admin: {
    addUserLocation: true,
    createCategory: true,
    createCategories: true,
    createLocation: true,
    createOrder: true,
    createPayment: true,
    createProduct: true,
    createUser: true,
    deleteAnOrderItem: true,
    deleteCategory: true,
    deleteOrder: true,
    deleteOrderItems: true,
    deleteProduct: true,
    deleteUserLocation: true,
    findFoods: true,
    getMyPayments: true,
    registerUser: true,
    updateOrder: true,
    updateOrderItems: true,
    updatePassword: true,
    updatePayment: true,
    updateProduct: true,
    updateUser: true,
    updateUserLocation: true,
    viewCategories: true,
    viewCategory: true,
    viewOrders: true,
    viewAllOrders: true,
    viewProducts: true,
    viewUsers: true,
    viewUser: true,
    viewLocations: true,
    viewStates: true,
    viewLgas: true,
    viewCountries: true,
  },
  user: {
    createOrder: true,
    updateOrder: true,
    deleteOrder: true,
    viewProducts: true,
    viewOrders: true,
    viewUser: true,
    addUserLocation: true,
    viewCategories: true,
    viewCategory: true,
    viewLocations: true,
    viewStates: true,
    viewLgas: true,
    viewCountries: true,
    deleteUser: true,
  },
  guest: {
    viewProducts: true,
    viewCategories: true,
    viewCategory: true,
    viewLocations: true,
    viewStates: true,
    viewLgas: true,
    viewCountries: true,
  },
};