"""update product model

Revision ID: 1570e9e9d6ca
Revises: 1f3275b030db
Create Date: 2024-05-13 11:43:48.944763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1570e9e9d6ca'
down_revision = '1f3275b030db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=35), nullable=False))
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', mysql.VARCHAR(length=35), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
