"""update category model

Revision ID: 1f3275b030db
Revises: 9c7aa8a42bdc
Create Date: 2024-05-10 15:58:13.604990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f3275b030db'
down_revision = '9c7aa8a42bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=35), nullable=False))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', mysql.VARCHAR(length=35), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
