"""update location

Revision ID: 3d334da116bb
Revises: be921680277e
Create Date: 2024-04-16 21:17:08.676992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d334da116bb'
down_revision = 'be921680277e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('continent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'country', ['country_id'], ['id'])

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'state', ['state_id'], ['id'])

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lga_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'lga', ['lga_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lga_id')

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('state_id')

    with op.batch_alter_table('continent', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('country_id')

    # ### end Alembic commands ###
