"""upgrade user

Revision ID: 4821c589b858
Revises: 771cc4be8d13
Create Date: 2024-04-17 23:35:40.371356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4821c589b858'
down_revision = '771cc4be8d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_seller_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address_buyer_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address_dispatcher_id', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'location', ['address_buyer_id'], ['id'])
        batch_op.create_foreign_key(None, 'location', ['address_dispatcher_id'], ['id'])
        batch_op.create_foreign_key(None, 'location', ['address_seller_id'], ['id'])
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('address_dispatcher_id')
        batch_op.drop_column('address_buyer_id')
        batch_op.drop_column('address_seller_id')

    # ### end Alembic commands ###
