"""update user model v5

Revision ID: 579ee4af07c2
Revises: 6cfae94aea63
Create Date: 2024-05-13 14:14:26.511110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579ee4af07c2'
down_revision = '6cfae94aea63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=70), nullable=True))
        batch_op.add_column('user', sa.Column('products', sa.relationship('Product', backref='owner',
                                                       foreign_keys='Product.user_id',
                                                       cascade='all, delete-orphan')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
