"""update user model v3

Revision ID: 6cfae94aea63
Revises: 1570e9e9d6ca
Create Date: 2024-05-13 14:13:36.901290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6cfae94aea63'
down_revision = '1570e9e9d6ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', mysql.VARCHAR(length=70), nullable=True))

    # ### end Alembic commands ###
