"""update location v3

Revision ID: 771cc4be8d13
Revises: e4669cadb2ea
Create Date: 2024-04-17 13:39:27.160850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771cc4be8d13'
down_revision = 'e4669cadb2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
