"""add password reset

Revision ID: 8141554e92fc
Revises: 771cc4be8d13
Create Date: 2024-04-19 18:20:47.267299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8141554e92fc'
down_revision = '771cc4be8d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_password_expiry_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('address_seller_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('address_buyer_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('address_dispatcher_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'location', ['address_dispatcher_id'], ['id'])
        batch_op.create_foreign_key(None, 'location', ['address_buyer_id'], ['id'])
        batch_op.create_foreign_key(None, 'location', ['address_seller_id'], ['id'])
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('address_dispatcher_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('address_buyer_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('address_seller_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('reset_password_expiry_date')

    # ### end Alembic commands ###
