"""update user: delete password expiry field

Revision ID: 9c0a80de01c8
Revises: 8141554e92fc
Create Date: 2024-04-19 19:27:57.626241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c0a80de01c8'
down_revision = '8141554e92fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_password_expiry_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_password_expiry_date', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
