"""update order, product and user models

Revision ID: 9c7aa8a42bdc
Revises: 2c00cb1ba716
Create Date: 2024-04-23 15:48:43.762318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7aa8a42bdc'
down_revision = '2c00cb1ba716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_token', sa.String(length=120), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('payment_token')

    # ### end Alembic commands ###
