"""setup all table and stores

Revision ID: be921680277e
Revises: 
Create Date: 2024-04-16 21:04:52.068436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be921680277e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.alter_column('continent_id',
               existing_type=mysql.VARCHAR(length=35),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('lga', schema=None) as batch_op:
        batch_op.alter_column('state_id',
               existing_type=mysql.VARCHAR(length=35),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.alter_column('country_id',
               existing_type=mysql.VARCHAR(length=35),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.alter_column('country_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=35),
               existing_nullable=False)

    with op.batch_alter_table('lga', schema=None) as batch_op:
        batch_op.alter_column('state_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=35),
               existing_nullable=False)

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.alter_column('continent_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=35),
               existing_nullable=False)

    # ### end Alembic commands ###
