"""update location v1

Revision ID: d5340952538b
Revises: 3d334da116bb
Create Date: 2024-04-17 13:19:37.144750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5340952538b'
down_revision = '3d334da116bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('continent')
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_constraint('country_ibfk_1', type_='foreignkey')
        batch_op.drop_column('continent_id')
        batch_op.drop_column('state_id')

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_constraint('state_ibfk_1', type_='foreignkey')
        batch_op.drop_column('lga_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lga_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('state_ibfk_1', 'lga', ['lga_id'], ['id'])

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('continent_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('country_ibfk_1', 'state', ['state_id'], ['id'])

    op.create_table('continent',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=35), nullable=False),
    sa.Column('country_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name='continent_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
