"""update payment models and some order models

Revision ID: dbd596ca2c57
Revises: e95954b59825
Create Date: 2024-05-27 11:29:39.780229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbd596ca2c57'
down_revision = 'e95954b59825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_payment_status', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('dispatcher_payment_status', sa.String(length=10), nullable=True))
        batch_op.alter_column('payment_date_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('total_amount')
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('total_amount', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('payment_date_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_column('dispatcher_payment_status')
        batch_op.drop_column('seller_payment_status')

    # ### end Alembic commands ###
