"""update location v2

Revision ID: e4669cadb2ea
Revises: d5340952538b
Create Date: 2024-04-17 13:31:03.217168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4669cadb2ea'
down_revision = 'd5340952538b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lga', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'state', ['state_id'], ['id'])

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('lga_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'country', ['country_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('lga_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('lga', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
