"""update the payment schema

Revision ID: e95954b59825
Revises: 25c4c66b8125
Create Date: 2024-05-24 19:54:25.882945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e95954b59825'
down_revision = '25c4c66b8125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dispatcher_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Integer(), nullable=True))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('total_amount')
        batch_op.drop_column('dispatcher_amount')
        batch_op.drop_column('seller_amount')

    # ### end Alembic commands ###
